export const MOCK_DESTINATIONS = [
  {
    id: "dst-001",
    name: "Rock-Hewn Churches of Lalibela",
    description: "Eleven monolithic churches carved directly into volcanic rock in the 12th–13th century, a UNESCO World Heritage Site.",
    region: "amhara",
    zone: "North Wollo",
    woreda: "Lalibela",
    latitude: "12.0319",
    longitude: "39.0474",
    category: "historical",
    historicalInfo: "Commissioned by King Lalibela in the late 12th century as a 'New Jerusalem'. The churches remain an active pilgrimage site for Ethiopian Orthodox Christians.",
    accessibility: "Accessible via daily flights from Addis Ababa to Lalibela Airport. Paved roads from airport to town. Some churches have uneven terrain and narrow passages.",
    seasonalInfo: "Best visited during the dry season (October–March). Peak pilgrimage during Timkat (January) and Genna (January 7). Expect cooler temperatures at altitude.",
    createdAt: "2026-03-10T08:00:00Z",
  },
  {
    id: "dst-002",
    name: "Simien Mountains National Park",
    description: "Dramatic escarpments and peaks reaching 4,620m, home to endemic wildlife including the gelada baboon and Ethiopian wolf.",
    region: "amhara",
    zone: "North Gondar",
    woreda: "Debark",
    latitude: "13.1833",
    longitude: "38.3667",
    category: "natural",
    historicalInfo: "Established as a national park in 1969. UNESCO World Heritage Site since 1978. The plateau is over 40 million years old.",
    accessibility: "Drive from Gondar (2–3 hours on paved road). 4WD recommended for park entrances. Trekking requires a local guide and park permit.",
    seasonalInfo: "Dry season (September–February) is ideal for trekking. Avoid the rainy season (June–August) when trails become dangerous. Best wildlife viewing at dawn.",
    createdAt: "2026-03-15T10:30:00Z",
  },
  {
    id: "dst-003",
    name: "Harar Jugol",
    description: "The walled city of Harar, with 82 mosques and 102 shrines, is the fourth holiest city of Islam.",
    region: "harari",
    zone: "Harar",
    woreda: "Harar",
    latitude: "9.3115",
    longitude: "42.1199",
    category: "cultural",
    historicalInfo: "Founded in the 7th century. The Jugol wall was built in the 16th century. Birthplace of Ras Tafari (Haile Selassie). Known as the 'City of Saints'.",
    accessibility: "30 minutes by air from Addis Ababa or 5 hours by road. Walkable city center. Cultural sites are clustered within the walled Jugol.",
    seasonalInfo: "Year-round destination. The dry season (October–February) is most comfortable. Harari cultural festivals occur throughout the year.",
    createdAt: "2026-04-01T14:00:00Z",
  },
  {
    id: "dst-004",
    name: "Danakil Depression",
    description: "One of the hottest and lowest places on Earth, featuring sulfur springs, salt flats, and active volcanoes.",
    region: "afar",
    zone: "Afar",
    woreda: "Eritre-Afar",
    latitude: "14.2500",
    longitude: "40.3000",
    category: "adventure",
    historicalInfo: "Part of the East African Rift system where three tectonic plates are pulling apart. The Afar people have mined salt here for millennia.",
    accessibility: "4WD convoy mandatory from Mekelle or Semera. Minimum 3-day guided expedition. No permanent infrastructure — camping only.",
    seasonalInfo: "Best from November–February. Temperatures exceed 50°C in summer (April–June). Always travel with experienced Afar guides.",
    createdAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "dst-005",
    name: "Lake Tana Monasteries",
    description: "Ethiopia's largest lake, dotted with islands housing medieval monasteries with vivid wall paintings.",
    region: "amhara",
    zone: "Lake Tana",
    woreda: "Bahir Dar",
    latitude: "11.6000",
    longitude: "37.4000",
    category: "religious",
    historicalInfo: "The monasteries date from the 14th century. Lake Tana is the source of the Blue Nile. Zege Peninsula and Tississat Falls are key sites.",
    accessibility: "Accessible from Bahir Dar (daily flights from Addis Ababa). Boat trips to island monasteries depart from Bahir Dar jetty. Tississat Falls 30km south by road.",
    seasonalInfo: "Visit during dry season (October–April). Lake level drops in dry months, making some monasteries easier to access. Birdwatching excellent October–March.",
    createdAt: "2026-04-20T11:00:00Z",
  },
  {
    id: "dst-006",
    name: "Bale Mountains",
    description: "Alpine plateaus and montane forests home to the largest population of Ethiopian wolves.",
    region: "oromia",
    zone: "Bale",
    woreda: "Goba",
    latitude: "6.9667",
    longitude: "39.7167",
    category: "wildlife",
    historicalInfo: "Established as a national park in 1970. The Harenna Forest is one of the last remaining Afromontane cloud forests. The Sanetti Plateau reaches 4,000m.",
    accessibility: "Drive from Addis Ababa (6–8 hours) or fly to Goba. 4WD required inside the park. Park fees and guide mandatory.",
    seasonalInfo: "Best during dry season (October–March). Ethiopian wolves are most visible at dawn on the Sanetti Plateau. Harenna Forest is accessible year-round.",
    createdAt: "2026-05-01T13:00:00Z",
  },
  {
    id: "dst-007",
    name: "Gondar Fasil Ghebbi",
    description: "A fortress enclosure of castles and churches from the 17th-century Gondarine period.",
    region: "amhara",
    zone: "North Gondar",
    woreda: "Gondar",
    latitude: "12.6089",
    longitude: "37.4590",
    category: "historical",
    historicalInfo: "Founded by Emperor Fasilides in 1636. The compound contains six castles, churches, and the Debre Berhan Selassie church with its famous ceiling paintings.",
    accessibility: "Daily flights from Addis Ababa to Gondar Airport. Fasil Ghebbi is within walking distance of the town center.",
    seasonalInfo: "Best October–February. Timkat festival (January) features a colorful procession to Fasilides' Bath. Dry season ideal for exploring the castles.",
    createdAt: "2026-05-10T10:00:00Z",
  },
  {
    id: "dst-008",
    name: "Arba Minch & Nechisar",
    description: "Twin lakes (Chamo and Abaya) flanked by the Nechisar National Park, with crocodile and hippo populations.",
    region: "snnp",
    zone: "Gamo Gofa",
    woreda: "Arba Minch",
    latitude: "6.0500",
    longitude: "37.5500",
    category: "natural",
    historicalInfo: "Arba Minch means 'forty springs' in Amharic. Nechisar (meaning 'white grass') was established as a national park in 1974. The Dorze people's bamboo huts are nearby.",
    accessibility: "Daily flights from Addis Ababa. Boat trips on Lake Chamo (hippo and crocodile viewing) depart from the park shore.",
    seasonalInfo: "Year-round destination. Boat trips best in dry season (October–March). The Dorze village visit is unaffected by season.",
    createdAt: "2026-05-20T15:00:00Z",
  },
]
