export const MOCK_CONTENT_ITEMS = [
  {
    id: "cnt-001",
    providerId: "prv-001",
    providerName: "Haile Resort & Spa",
    category: "hotel",
    contentType: "IMAGE",
    title: "Resort lobby photo",
    description: "Main lobby entrance with traditional Ethiopian artwork and modern furnishings.",
    thumbnail: null,
    uploadedAt: "2026-08-10T09:00:00Z",
    status: "PENDING_REVIEW",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-002",
    providerId: "prv-001",
    providerName: "Haile Resort & Spa",
    category: "hotel",
    contentType: "DESCRIPTION",
    title: "Spa services description",
    description: "Detailed description of spa and wellness offerings including traditional Ethiopian coffee ceremonies and modern treatments.",
    thumbnail: null,
    uploadedAt: "2026-08-10T09:15:00Z",
    status: "PENDING_REVIEW",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-003",
    providerId: "prv-002",
    providerName: "Ethiopian Horizons Tours",
    category: "agency",
    contentType: "PACKAGE",
    title: "10-Day Northern Heritage Trail",
    description: "Multi-day package covering Lalibela, Axum, Gondar, and Simien Mountains with accommodation and guided tours.",
    thumbnail: null,
    uploadedAt: "2026-08-11T10:30:00Z",
    status: "PENDING_REVIEW",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-004",
    providerId: "prv-002",
    providerName: "Ethiopian Horizons Tours",
    category: "agency",
    contentType: "IMAGE",
    title: "Group tour at Axum stelae",
    description: "Photo of a guided group visiting the Axum archaeological site.",
    thumbnail: null,
    uploadedAt: "2026-08-11T10:45:00Z",
    status: "PENDING_REVIEW",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-005",
    providerId: "prv-003",
    providerName: "Addis Car Rentals",
    category: "transport",
    contentType: "IMAGE",
    title: "Fleet showcase - Toyota Land Cruiser",
    description: "Photo of the flagship 4WD vehicle available for hire.",
    thumbnail: null,
    uploadedAt: "2026-08-12T14:00:00Z",
    status: "APPROVED",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-006",
    providerId: "prv-003",
    providerName: "Addis Car Rentals",
    category: "transport",
    contentType: "VIDEO",
    title: "Fleet walkaround video",
    description: "Walkaround video showing vehicle interiors and safety features.",
    thumbnail: null,
    uploadedAt: "2026-08-12T14:30:00Z",
    status: "FLAGGED",
    flagReason: "Video contains watermarked footage from a third-party source.",
    editNote: null,
  },
  {
    id: "cnt-007",
    providerId: "prv-004",
    providerName: "Abebe Kebede",
    category: "driver",
    contentType: "DESCRIPTION",
    title: "Driver bio update",
    description: "Updated personal bio highlighting recent certifications and language proficiency.",
    thumbnail: null,
    uploadedAt: "2026-08-13T08:00:00Z",
    status: "PENDING_REVIEW",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-008",
    providerId: "prv-008",
    providerName: "Fatuma Ali",
    category: "driver",
    contentType: "PACKAGE",
    title: "Harar Cultural Day Trip",
    description: "Full-day guided tour of Harar Jugol including the hyena feeding experience and colorful markets.",
    thumbnail: null,
    uploadedAt: "2026-08-13T11:00:00Z",
    status: "EDIT_REQUESTED",
    flagReason: null,
    editNote: "Please add pricing details and included/excluded items to the package listing.",
  },
  {
    id: "cnt-009",
    providerId: "prv-001",
    providerName: "Haile Resort & Spa",
    category: "hotel",
    contentType: "IMAGE",
    title: "Pool area at sunset",
    description: "Aerial view of the infinity pool overlooking the city at golden hour.",
    thumbnail: null,
    uploadedAt: "2026-08-14T07:30:00Z",
    status: "PENDING_REVIEW",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-010",
    providerId: "prv-007",
    providerName: "Lalibela Heritage Tours",
    category: "agency",
    contentType: "PACKAGE",
    title: "Rock Churches Day Tour",
    description: "Full-day guided tour of all 11 rock-hewn churches of Lalibela.",
    thumbnail: null,
    uploadedAt: "2026-08-14T12:00:00Z",
    status: "PENDING_REVIEW",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-011",
    providerId: "prv-002",
    providerName: "Ethiopian Horizons Tours",
    category: "agency",
    contentType: "VIDEO",
    title: "Client testimonial compilation",
    description: "Compilation of client testimonials from recent tours.",
    thumbnail: null,
    uploadedAt: "2026-08-15T09:00:00Z",
    status: "APPROVED",
    flagReason: null,
    editNote: null,
  },
  {
    id: "cnt-012",
    providerId: "prv-003",
    providerName: "Addis Car Rentals",
    category: "transport",
    contentType: "DESCRIPTION",
    title: "Updated rental terms",
    description: "Revised rental terms and conditions including new insurance options.",
    thumbnail: null,
    uploadedAt: "2026-08-15T15:00:00Z",
    status: "PENDING_REVIEW",
    flagReason: null,
    editNote: null,
  },
]
