export const MOCK_PROVIDERS = [
  {
    id: "prv-001",
    businessName: "Haile Resort & Spa",
    category: "hotel",
    email: "haile@resort.et",
    phone: "+251911223344",
    address: "Bole Road, Addis Ababa",
    registeredAt: "2026-07-15T08:30:00Z",
    status: "UNDER_REVIEW",
    rejectionReason: null,
    statusNote: null,
    registrationData: {
      name: "Haile Resort & Spa",
      businessType: "resort",
      address: "Bole Road, Addis Ababa",
      latitude: "9.0054",
      longitude: "38.7636",
      contact: "+251911223344",
      starRating: "5",
      checkInTime: "14:00",
      checkOutTime: "11:00",
      currency: "ETB",
      description: "Luxury resort and spa in the heart of Addis Ababa with panoramic city views.",
      policies: "Free cancellation up to 48 hours before check-in. No pets allowed.",
      roomTypes: ["single", "double", "suite"],
      amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Gym"],
      paymentMethods: ["cash", "card", "mobile"],
    },
    documents: {
      businessLicense: { name: "business_license.pdf", status: "success" },
      ownershipDoc: { name: "ownership_agreement.pdf", status: "success" },
      bankInfo: { name: "bank_details.pdf", status: "success" },
    },
  },
  {
    id: "prv-002",
    businessName: "Ethiopian Horizons Tours",
    category: "agency",
    email: "info@horizonstours.et",
    phone: "+251922334455",
    address: "Meskel Square, Addis Ababa",
    registeredAt: "2026-07-18T10:15:00Z",
    status: "UNDER_REVIEW",
    rejectionReason: null,
    statusNote: null,
    registrationData: {
      agencyName: "Ethiopian Horizons Tours",
      businessRegistration: "BRN-2026-0452",
      agencyType: "inbound",
      yearEstablished: "2018",
      currency: "ETB",
      specialties: ["Historical", "Cultural", "Adventure"],
      tourTypes: ["group", "private", "multi-day"],
      description: "Award-winning tour operator specializing in Ethiopian cultural and historical tours.",
      paymentMethods: ["cash", "card", "mobile"],
    },
    documents: {
      businessLicense: { name: "business_registration.pdf", status: "success" },
      tourOperatorLicense: { name: "tour_operator_license.pdf", status: "success" },
      bankInfo: { name: "bank_account.pdf", status: "success" },
    },
  },
  {
    id: "prv-003",
    businessName: "Addis Car Rentals",
    category: "transport",
    email: "fleet@addiscar.et",
    phone: "+251933445566",
    address: "Airport Road, Addis Ababa",
    registeredAt: "2026-07-20T14:45:00Z",
    status: "VERIFIED",
    rejectionReason: null,
    statusNote: "Documents verified and approved.",
    registrationData: {
      companyName: "Addis Car Rentals",
      fleetSize: "11-25",
      vehicleTypes: ["sedan", "suv", "van"],
      transmission: "automatic",
      currency: "ETB",
      pickupLocations: ["Bole Airport", "Piazza", "Merkato"],
      dropoffLocations: ["Bole Airport", "Arba Minch", "Lalibela"],
      description: "Reliable car rental service with well-maintained fleet and professional drivers.",
      paymentMethods: ["cash", "card"],
    },
    documents: {
      businessLicense: { name: "business_license.pdf", status: "success" },
      vehicleDocs: { name: "vehicle_registrations.pdf", status: "success" },
      bankInfo: { name: "bank_info.pdf", status: "success" },
    },
  },
  {
    id: "prv-004",
    businessName: "Abebe Kebede",
    category: "driver",
    email: "abebe.k@gmail.com",
    phone: "+251944556677",
    address: "Bole, Addis Ababa",
    registeredAt: "2026-07-22T09:00:00Z",
    status: "UNDER_REVIEW",
    rejectionReason: null,
    statusNote: null,
    registrationData: {
      fullName: "Abebe Kebede",
      licenseNumber: "DL-2024-8812",
      licenseExpiry: "2028-12-31",
      experienceLevel: "experienced",
      languages: ["Amharic", "English", "Oromo"],
      vehicleAvailable: true,
      bio: "Professional tour guide and driver with 8 years of experience across Ethiopia.",
    },
    documents: {
      driverLicense: { name: "drivers_license.pdf", status: "success" },
      nationalId: { name: "national_id.pdf", status: "success" },
      bankInfo: null,
    },
  },
  {
    id: "prv-005",
    businessName: "Simien Lodge",
    category: "hotel",
    email: "reservations@simienlodge.et",
    phone: "+251955667788",
    address: "Gondar, Amhara Region",
    registeredAt: "2026-07-25T11:30:00Z",
    status: "REJECTED",
    rejectionReason: "Bank document is illegible. Please re-upload a clear scan of your bank details.",
    statusNote: null,
    registrationData: {
      name: "Simien Lodge",
      businessType: "lodge",
      address: "Gondar, Amhara Region",
      latitude: "13.2500",
      longitude: "38.1667",
      contact: "+251955667788",
      starRating: "3",
      checkInTime: "12:00",
      checkOutTime: "10:00",
      currency: "ETB",
      description: "Eco-lodge near the Simien Mountains National Park.",
      policies: "Non-refundable deposit required.",
      roomTypes: ["single", "double"],
      amenities: ["WiFi", "Restaurant"],
      paymentMethods: ["cash"],
    },
    documents: {
      businessLicense: { name: "business_license.pdf", status: "success" },
      ownershipDoc: { name: "lease_agreement.pdf", status: "success" },
      bankInfo: { name: "bank_scan_blurry.jpg", status: "success" },
    },
  },
  {
    id: "prv-006",
    businessName: "Blue Nile Express",
    category: "transport",
    email: "ops@bluenileexpress.et",
    phone: "+251966778899",
    address: "Mekelle, Tigray Region",
    registeredAt: "2026-06-10T08:00:00Z",
    status: "SUSPENDED",
    rejectionReason: null,
    statusNote: "Suspended due to repeated customer complaints about vehicle condition.",
    registrationData: {
      companyName: "Blue Nile Express",
      fleetSize: "26-50",
      vehicleTypes: ["bus", "minibus", "van"],
      transmission: "manual",
      currency: "ETB",
      pickupLocations: ["Mekelle", "Axum", "Shire"],
      dropoffLocations: ["Mekelle", "Lalibela", "Gondar"],
      description: "Regional transport provider serving northern Ethiopia.",
      paymentMethods: ["cash"],
    },
    documents: {
      businessLicense: { name: "business_license.pdf", status: "success" },
      vehicleDocs: { name: "vehicle_registrations.pdf", status: "success" },
      bankInfo: { name: "bank_info.pdf", status: "success" },
    },
  },
  {
    id: "prv-007",
    businessName: "Lalibela Heritage Tours",
    category: "agency",
    email: "book@lalibelatours.et",
    phone: "+251977889900",
    address: "Lalibela, Amhara Region",
    registeredAt: "2026-08-01T16:00:00Z",
    status: "UNDER_REVIEW",
    rejectionReason: null,
    statusNote: null,
    registrationData: {
      agencyName: "Lalibela Heritage Tours",
      businessRegistration: "BRN-2026-0891",
      agencyType: "inbound",
      yearEstablished: "2022",
      currency: "ETB",
      specialties: ["Religious", "Historical", "Photography"],
      tourTypes: ["group", "day-trip"],
      description: "Specialized tours of the rock-hewn churches of Lalibela.",
      paymentMethods: ["cash", "mobile"],
    },
    documents: {
      businessLicense: { name: "business_registration.pdf", status: "success" },
      tourOperatorLicense: null,
      bankInfo: { name: "bank_account.pdf", status: "success" },
    },
  },
  {
    id: "prv-008",
    businessName: "Fatuma Ali",
    category: "driver",
    email: "fatuma.ali@yahoo.com",
    phone: "+251988990011",
    address: "Dire Dawa",
    registeredAt: "2026-08-05T13:20:00Z",
    status: "VERIFIED",
    rejectionReason: null,
    statusNote: "All documents verified.",
    registrationData: {
      fullName: "Fatuma Ali",
      licenseNumber: "DL-2025-3347",
      licenseExpiry: "2029-06-15",
      experienceLevel: "professional",
      languages: ["Amharic", "English", "Somali", "Arabic"],
      vehicleAvailable: true,
      bio: "Licensed guide and driver covering eastern Ethiopia, including Harar and Dire Dawa.",
    },
    documents: {
      driverLicense: { name: "drivers_license.pdf", status: "success" },
      nationalId: { name: "national_id.pdf", status: "success" },
      bankInfo: { name: "bank_info.pdf", status: "success" },
    },
  },
]
