export const AGENT_TYPES = {
  supervisor: { label: "Supervisor Agent", color: "#0f9d58" },
  destination: { label: "Destination Agent", color: "#2563eb" },
  flight: { label: "Flight Agent", color: "#7c3aed" },
  budget: { label: "Budget Agent", color: "#ea580c" },
  itinerary: { label: "Itinerary Agent", color: "#0891b2" },
  accommodation: { label: "Accommodation Agent", color: "#ca8a04" },
}

export const RUN_STATUSES = {
  COMPLETED: { label: "Completed", tone: "green" },
  RUNNING: { label: "Running", tone: "brand" },
  FAILED: { label: "Failed", tone: "red" },
  AWAITING_APPROVAL: { label: "Awaiting Approval", tone: "amber" },
}

export const MOCK_AGENT_RUNS = [
  {
    id: "run-001",
    agent: "supervisor",
    task: "Plan a 5-day trip to Lalibela for 2 travelers with a mid-range budget",
    inputParams: { destination: "Lalibela", travelers: 2, duration: "5 days", budget: "mid-range" },
    toolsCalled: ["destination_lookup", "budget_calc", "itinerary_generator"],
    toolResults: [
      { tool: "destination_lookup", result: "Found 3 available packages for Lalibela" },
      { tool: "budget_calc", result: "Estimated mid-range budget: 65,000 ETB per person" },
      { tool: "itinerary_generator", result: "Generated 5-day itinerary with 4 activities" },
    ],
    decisions: "Dispatched to Destination Agent, Budget Agent, and Itinerary Agent. Aggregated results into final recommendation.",
    duration: "3.2s",
    tokenUsage: 1847,
    userApproval: "Auto-approved",
    outcome: "success",
    status: "COMPLETED",
    timestamp: "2026-08-18T10:15:00Z",
  },
  {
    id: "run-002",
    agent: "supervisor",
    task: "Search for round-trip flights from Addis Ababa to Gondar on August 25",
    inputParams: { origin: "ADD", destination: "GDQ", date: "2026-08-25", type: "round-trip" },
    toolsCalled: ["flight_search"],
    toolResults: [
      { tool: "flight_search", result: "Found 3 flights: ET120 (6:30, $185), ET134 (9:00, $210), ET156 (14:00, $195)" },
    ],
    decisions: "Flight Agent returned options. Recommending ET120 (earliest, cheapest).",
    duration: "1.8s",
    tokenUsage: 892,
    userApproval: "Pending",
    outcome: "success",
    status: "AWAITING_APPROVAL",
    timestamp: "2026-08-18T10:16:30Z",
  },
  {
    id: "run-003",
    agent: "destination",
    task: "Look up accessibility information for Simien Mountains National Park",
    inputParams: { destination: "Simien Mountains", infoType: "accessibility" },
    toolsCalled: ["destination_lookup"],
    toolResults: [
      { tool: "destination_lookup", result: "Paved road from Gondar (2-3 hrs). 4WD required inside park. Guide and permit mandatory." },
    ],
    decisions: "Returned accessibility data directly. No further dispatch needed.",
    duration: "0.9s",
    tokenUsage: 423,
    userApproval: "N/A",
    outcome: "success",
    status: "COMPLETED",
    timestamp: "2026-08-18T10:17:00Z",
  },
  {
    id: "run-004",
    agent: "budget",
    task: "Calculate total cost estimate for a 7-day Northern Circuit tour (2 travelers)",
    inputParams: { packageId: "pkg-1", travelers: 2, duration: 7 },
    toolsCalled: ["price_lookup", "fee_calculator", "budget_calc"],
    toolResults: [
      { tool: "price_lookup", result: "Base package price: 48,500 ETB per person" },
      { tool: "fee_calculator", result: "Park fees: 2,400 ETB, Guide surcharge: 3,500 ETB" },
      { tool: "budget_calc", result: "Total: 104,800 ETB for 2 travelers (52,400 per person)" },
    ],
    decisions: "Applied early-bird discount of 5%. Final estimate: 99,560 ETB.",
    duration: "2.1s",
    tokenUsage: 1156,
    userApproval: "Auto-approved",
    outcome: "success",
    status: "COMPLETED",
    timestamp: "2026-08-18T10:18:15Z",
  },
  {
    id: "run-005",
    agent: "flight",
    task: "Search for one-way flight from Dire Dawa to Addis Ababa on September 1",
    inputParams: { origin: "DIR", destination: "ADD", date: "2026-09-01", type: "one-way" },
    toolsCalled: ["flight_search"],
    toolResults: [
      { tool: "flight_search", result: "Error: No flights available on this route for the selected date" },
    ],
    decisions: "Flight Agent could not find available flights. Flagging for retry with flexible dates.",
    duration: "1.4s",
    tokenUsage: 567,
    userApproval: "N/A",
    outcome: "no_results",
    status: "FAILED",
    timestamp: "2026-08-18T10:19:00Z",
  },
  {
    id: "run-006",
    agent: "itinerary",
    task: "Generate a detailed day-by-day itinerary for Harar cultural tour (3 days)",
    inputParams: { destination: "Harar", duration: "3 days", interests: ["cultural", "food", "history"] },
    toolsCalled: ["destination_lookup", "activity_search", "itinerary_generator"],
    toolResults: [
      { tool: "destination_lookup", result: "Harar Jugol: 82 mosques, 102 shrines, Rewda coffee ceremony" },
      { tool: "activity_search", result: "Found 8 activities: Jugol walk,hyena feeding, coffee ceremony, market tour" },
      { tool: "itinerary_generator", result: "3-day itinerary: Day 1 Jugol walls, Day 2 markets & culture, Day 3 hyena feeding & departure" },
    ],
    decisions: "Prioritized UNESCO sites and unique cultural experiences. Included traditional Harari meals.",
    duration: "2.7s",
    tokenUsage: 1534,
    userApproval: "Auto-approved",
    outcome: "success",
    status: "COMPLETED",
    timestamp: "2026-08-18T10:20:00Z",
  },
  {
    id: "run-007",
    agent: "accommodation",
    task: "Find available hotels in Gondar for August 25–27 (2 guests)",
    inputParams: { destination: "Gondar", checkIn: "2026-08-25", checkOut: "2026-08-27", guests: 2 },
    toolsCalled: ["inventory_search", "price_lookup"],
    toolResults: [
      { tool: "inventory_search", result: "Found 4 available rooms across 2 hotels" },
      { tool: "price_lookup", result: "Price range: 2,800–6,500 ETB per night" },
    ],
    decisions: "Sorted by price-to-quality ratio. Recommended Haile Resort suite at 6,500/night for mid-range.",
    duration: "1.6s",
    tokenUsage: 743,
    userApproval: "Auto-approved",
    outcome: "success",
    status: "COMPLETED",
    timestamp: "2026-08-18T10:21:00Z",
  },
  {
    id: "run-008",
    agent: "supervisor",
    task: "Full trip planning: Addis Ababa → Lalibela → Gondar, 8 days, 2 travelers, high budget",
    inputParams: { origin: "ADD", destinations: ["Lalibela", "Gondar"], duration: "8 days", travelers: 2, budget: "high" },
    toolsCalled: ["flight_search", "destination_lookup", "budget_calc", "itinerary_generator", "accommodation_lookup"],
    toolResults: [
      { tool: "flight_search", result: "Found connecting flights: ADD→LAL, GDQ→ADD" },
      { tool: "destination_lookup", result: "Retrieved data for Lalibela and Gondar destinations" },
      { tool: "budget_calc", result: "High-budget estimate: 180,000 ETB total" },
      { tool: "itinerary_generator", result: "8-day multi-city itinerary generated" },
      { tool: "accommodation_lookup", result: "Selected luxury options in both cities" },
    ],
    decisions: "Coordinated 5 sub-agents. Optimized route to avoid backtracking. Recommended direct ADD→LAL, then overland to Gondar, return GDQ→ADD.",
    duration: "5.4s",
    tokenUsage: 3241,
    userApproval: "Pending",
    outcome: "success",
    status: "AWAITING_APPROVAL",
    timestamp: "2026-08-18T10:22:00Z",
  },
  {
    id: "run-009",
    agent: "budget",
    task: "Re-calculate trip cost with updated hotel selection (luxury upgrade)",
    inputParams: { tripId: "trip-008", hotelChange: "upgrade to luxury" },
    toolsCalled: ["price_lookup", "budget_calc"],
    toolResults: [
      { tool: "price_lookup", result: "Luxury hotel delta: +4,200 ETB/night × 7 nights = +29,400 ETB" },
      { tool: "budget_calc", result: "Revised total: 209,400 ETB (was 180,000 ETB)" },
    ],
    decisions: "Applied 3% loyalty discount. Final: 203,118 ETB.",
    duration: "1.3s",
    tokenUsage: 678,
    userApproval: "N/A",
    outcome: "success",
    status: "COMPLETED",
    timestamp: "2026-08-18T10:23:00Z",
  },
  {
    id: "run-010",
    agent: "supervisor",
    task: "Handle user cancellation request for trip-008",
    inputParams: { tripId: "trip-008", reason: "change of plans" },
    toolsCalled: ["booking_cancel", "refund_calculator"],
    toolResults: [
      { tool: "booking_cancel", result: "Booking trip-008 cancelled successfully" },
      { tool: "refund_calculator", result: "Refund eligible: 85% of total (203,118 × 0.85 = 172,650 ETB)" },
    ],
    decisions: "Cancellation within 48-hour window. 15% cancellation fee applied per policy.",
    duration: "2.0s",
    tokenUsage: 923,
    userApproval: "Auto-approved",
    outcome: "success",
    status: "COMPLETED",
    timestamp: "2026-08-18T10:24:00Z",
  },
]

export const MOCK_WORKFLOWS = [
  {
    id: "wf-001",
    runId: "run-001",
    label: "Lalibela 5-Day Trip Plan",
    startedAt: "2026-08-18T10:15:00Z",
    totalDuration: "3.2s",
    status: "COMPLETED",
    nodes: [
      {
        id: "wf-001-a",
        agent: "supervisor",
        task: "Coordinate trip planning for 5-day Lalibela visit",
        status: "COMPLETED",
        duration: "3.2s",
        children: [
          {
            id: "wf-001-b",
            agent: "destination",
            task: "Fetch Lalibela destination data and available packages",
            status: "COMPLETED",
            duration: "0.8s",
            children: [],
          },
          {
            id: "wf-001-c",
            agent: "budget",
            task: "Calculate mid-range budget estimate for 2 travelers",
            status: "COMPLETED",
            duration: "1.1s",
            children: [],
          },
          {
            id: "wf-001-d",
            agent: "itinerary",
            task: "Generate 5-day itinerary with cultural activities",
            status: "COMPLETED",
            duration: "1.5s",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "wf-002",
    runId: "run-008",
    label: "Multi-City 8-Day Trip",
    startedAt: "2026-08-18T10:22:00Z",
    totalDuration: "5.4s",
    status: "AWAITING_APPROVAL",
    nodes: [
      {
        id: "wf-002-a",
        agent: "supervisor",
        task: "Plan Addis→Lalibela→Gondar 8-day luxury trip",
        status: "RUNNING",
        duration: "5.4s",
        children: [
          {
            id: "wf-002-b",
            agent: "flight",
            task: "Search ADD→LAL and GDQ→ADD flights",
            status: "COMPLETED",
            duration: "1.8s",
            children: [],
          },
          {
            id: "wf-002-c",
            agent: "destination",
            task: "Gather destination info for Lalibela and Gondar",
            status: "COMPLETED",
            duration: "0.9s",
            children: [],
          },
          {
            id: "wf-002-d",
            agent: "accommodation",
            task: "Select luxury hotels in both cities",
            status: "COMPLETED",
            duration: "1.6s",
            children: [],
          },
          {
            id: "wf-002-e",
            agent: "budget",
            task: "Calculate total high-budget estimate",
            status: "COMPLETED",
            duration: "2.1s",
            children: [],
          },
          {
            id: "wf-002-f",
            agent: "itinerary",
            task: "Generate multi-city 8-day itinerary",
            status: "RUNNING",
            duration: "3.0s",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "wf-003",
    runId: "run-005",
    label: "Dire Dawa Flight Search",
    startedAt: "2026-08-18T10:19:00Z",
    totalDuration: "1.4s",
    status: "FAILED",
    nodes: [
      {
        id: "wf-003-a",
        agent: "supervisor",
        task: "Search DIR→ADD flight on Sep 1",
        status: "FAILED",
        duration: "1.4s",
        children: [
          {
            id: "wf-003-b",
            agent: "flight",
            task: "Query available flights for DIR→ADD route",
            status: "FAILED",
            duration: "1.4s",
            children: [],
          },
        ],
      },
    ],
  },
]
